--drop user c##board2 CASCADE;
--계정생성
CREATE USER c##board2 IDENTIFIED BY board4321
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    PROFILE DEFAULT;
--권한부여
GRANT CONNECT, RESOURCE TO c##board2;
GRANT CREATE VIEW, CREATE SYNONYM TO c##board2;
GRANT UNLIMITED TABLESPACE TO c##board2;
--락 풀기
ALTER USER c##board2 ACCOUNT UNLOCK;