drop user c##board CASCADE;
--계정생성
CREATE USER c##board IDENTIFIED BY board1234
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    PROFILE DEFAULT;
--권한부여
GRANT CONNECT, RESOURCE TO c##board;
GRANT CREATE VIEW, CREATE SYNONYM TO c##board;
GRANT UNLIMITED TABLESPACE TO c##board;
--락 풀기
ALTER USER c##board ACCOUNT UNLOCK;